---
name: Issue Comment

on:
  issue_comment:
    types: [created]

permissions:
  contents: read

jobs:
  remove-if-waiting:
    uses: ./.github/workflows/remove-issue-label.yml
    permissions:
      contents: read
      issues: write
    with:
      label-name: "awaiting-response"
  remove-if-stale:
    uses: ./.github/workflows/remove-issue-label.yml
    permissions:
      contents: read
      issues: write
    with:
      label-name: "stale"
